#!/bin/bash

if test $# -ne 1
then
    echo 'mkshell file'
else
    if [ -f $1 ]
    then
	echo "warning: file $1 exists"
    else
	echo '#!/bin/bash' > $1
	echo ' ' >> $1
        if [[ ! -z $2 ]]
        then
          echo "if [[ \$# -ne $2 ]]; then" >> $1
          echo "  echo 'Usage: $1 <>'" >> $1
          echo "  exit 1" >> $1
          echo "fi" >> $1
        fi

	chmod a+x $1
	echo "$1 created"
    fi
fi
